Game logic
mkotyak/stanford_cs193p_set_card_game pull request #3
Opened 2022-07-18 10:39 UTC by mkotyak

2022-07-18 12:21 UTC, garbalinskiy requested changes

2022-07-18 12:21 UTC, garbalinskiy commented on Set/Card/CardViewModel.swift
> +    var shape: Image {
Here is not exactly clear what is `shape`, so in this case I would recommend to name it `shapeImage`

2022-07-18 12:21 UTC, garbalinskiy commented on Set/Game/GameViewModel.swift
> +    var potentialSet: [CardModel] = []
I would recommend to use here a `Set<CardModel>` and not array to easy check if existing, add and remove

2022-07-18 12:21 UTC, garbalinskiy commented on Set/Game/GameViewModel.swift
> +        guard let chousenCard = cardsOnScreen.filter({$0.id == card.id}).first else {
You can use function of array `.first(where: {..}` but it general this is good solution

2022-07-18 12:21 UTC, garbalinskiy commented on Set/Game/GameViewModel.swift
> +        if potentialSet.isEmpty {
I would change here logic if use `Set<CardModel>` instead of Array, 
e.g. 
1. check what I should do with card, remove from set or add to it,
2. then check if I have three of it, after any changes (assuming we cannot have more than 2 when we start this check)

2022-07-18 12:21 UTC, garbalinskiy commented on Set/Models/GameModel.swift
> +        for _ in 1 ... 12 {
You already know to to move an hardcoded value to Constants

2022-07-18 12:21 UTC, garbalinskiy commented on Set/Models/GameModel.swift
> +        for _ in 0 ..< min(3, deck.count) {
You can move this to the Contacts too

2022-07-18 12:21 UTC, garbalinskiy commented on Set/Models/GameModel.swift
> +        guard let chousenIndex = cardsOnTheScreen.firstIndex(where: {$0.id == cardId}) else {
It seems that you store `isActive` or selected state in two places, either you should do it in `GameModel` and everytime filter card where `isActive` is true, or card itself doesn't know about it's state in cardCade you add this state on the level of ViewModel.

2022-07-18 12:35 UTC, mkotyak commented on Set/Models/GameModel.swift
> +        for _ in 1 ... 12 {
yes, I'll do it later, when will clean the code

2022-07-18 12:35 UTC, mkotyak commented on Set/Models/GameModel.swift
> +        for _ in 0 ..< min(3, deck.count) {
yes, I agree

2022-07-18 12:39 UTC, mkotyak commented on Set/Card/CardViewModel.swift
> +    var shape: Image {
fixed

2022-07-18 12:40 UTC, mkotyak commented on Set/Game/GameViewModel.swift
> +        guard let chousenCard = cardsOnScreen.filter({$0.id == card.id}).first else {
fixed

2022-07-19 06:54 UTC, garbalinskiy approved these changes

2022-07-19 06:54 UTC, garbalinskiy commented on Set/Models/GameModel.swift
> +    private func checkASet(for setOfCards: [CardModel]) -> Bool {
I would name if `of cards`

2022-07-19 06:54 UTC, garbalinskiy commented on Set/Models/GameModel.swift
> +        print("Make cards green")
This is a good practice to leave a print in a developing process to have uderstanding what is going on

2022-07-19 08:26 UTC, merged